# Generated by Django 2.2 on 2021-02-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(help_text='Выберите группу из списка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='users.Group', verbose_name='Группа'),
        ),
    ]
