# Generated by Django 2.2 on 2021-02-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='allow_manage',
            field=models.BooleanField(default=False, help_text='Открывает пользователю функционал проверки работ', null=True, verbose_name='Доступ к управлению'),
        ),
    ]
