# Generated by Django 2.2 on 2021-02-26 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210223_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(help_text='Выберите группу из списка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.Group', verbose_name='Группа'),
        ),
    ]
