# Generated by Django 2.2 on 2021-03-17 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата проверки')),
                ('info', models.TextField(blank=True, help_text='При необходимости укажите дополнительные сведения', max_length=1000, null=True, verbose_name='Сопровотельная информация')),
                ('status', models.BooleanField(default=False, help_text='Укажите текущий статус проверки', null=True, verbose_name='Текущий статус проверки работы')),
                ('docx_file', models.FileField(help_text='Укажите файл с дипломной работой', upload_to='diplomas/%Y/%m/%d/', verbose_name='Файл с дипломной работой')),
                ('student', models.ForeignKey(help_text='Выберите студента из списка', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_student', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'ordering': ['check_date'],
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField(help_text='Укажите раздел ПЗ', max_length=100, verbose_name='Раздел ПЗ страницы')),
                ('page_number', models.PositiveSmallIntegerField(help_text='Укажите номер страницы', verbose_name='Номер страницы')),
                ('paragraph', models.PositiveSmallIntegerField(blank=True, help_text='Укажите номер абзаца', null=True, verbose_name='Номер абзаца')),
                ('text', models.TextField(help_text='Введите текст замечания', max_length=1000, verbose_name='Текст замечания')),
                ('note', models.TextField(blank=True, help_text='Введите текст примечания', max_length=2000, null=True, verbose_name='Текст примечания')),
                ('check_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации замечания')),
                ('author', models.ForeignKey(help_text='Укажите автора замечания', on_delete=django.db.models.deletion.CASCADE, related_name='remark', to=settings.AUTH_USER_MODEL, verbose_name='Автор замечания')),
                ('check_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='verify.CheckOut')),
            ],
            options={
                'ordering': ['check_date'],
            },
        ),
    ]
