# Generated by Django 2.2 on 2021-02-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='slug',
        ),
    ]
