# Generated by Django 2.2 on 2021-03-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='note',
        ),
    ]
