# Generated by Django 2.2 on 2021-03-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='check_all',
            field=models.CharField(blank=True, help_text='При необходимости укажите дополнительные сведения', max_length=100, null=True, verbose_name='Сопроводительная информация'),
        ),
    ]
