# Generated by Django 2.2 on 2021-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_remove_remark_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Укажите номер страницы', null=True, verbose_name='Номер страницы'),
        ),
    ]
