# Generated by Django 2.2 on 2021-03-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_remark_check_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='page_number',
            field=models.CharField(blank=True, help_text='Укажите номер страницы', max_length=100, null=True, verbose_name='Номер страницы'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='paragraph',
            field=models.CharField(blank=True, help_text='Укажите номер абзаца', max_length=100, null=True, verbose_name='Номер абзаца'),
        ),
    ]
