# Generated by Django 2.2 on 2021-02-25 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_remove_checkout_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['check_date']},
        ),
    ]
