# Generated by Django 2.2 on 2021-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0003_auto_20210319_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Укажите файл с дипломной работой с расширением pdf', null=True, upload_to='diplomas/%Y/%m/%d/', verbose_name='Файл с дипломной работой (расширение pdf)'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='docx_file',
            field=models.FileField(help_text='Укажите файл с дипломной работой с расширением docx', upload_to='diplomas/%Y/%m/%d/', verbose_name='Файл с дипломной работой (расширение docx)'),
        ),
    ]
