# Generated by Django 2.2 on 2021-03-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0004_auto_20210321_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='docx_file',
            field=models.FileField(help_text='Укажите файл с расширением docx', upload_to='diplomas/%Y/%m/%d/', verbose_name='Дипломная работа (расширение docx)'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pdf_file',
            field=models.FileField(help_text='Укажите файл с расширением pdf', null=True, upload_to='diplomas/%Y/%m/%d/', verbose_name='Дипломная работа (расширение pdf)'),
        ),
    ]
