# Generated by Django 2.2 on 2021-03-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0005_auto_20210322_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='check_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Укажите дату проверки', verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='docx_file',
            field=models.FileField(help_text='Укажите файл с расширением docx', null=True, upload_to='diplomas/%Y/%m/%d/', verbose_name='Дипломная работа (расширение docx)'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='check_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Укажите дату публикации замечания', verbose_name='Дата публикации замечания'),
        ),
    ]
