# Generated by Django 2.2 on 2021-03-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0006_auto_20210329_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='text',
            field=models.TextField(help_text='Введите текст замечания', max_length=300, verbose_name='Текст замечания'),
        ),
    ]
